## Problem 2

## Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
## 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
## By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.


def fibonacci(uptothisvalue):
    num1 = 1
    newfib = 2
    fib = [1, 2]
    while newfib <= uptothisvalue:
        num2 = newfib
        newfib = num1 + num2
        if newfib <= uptothisvalue:
            fib.append(newfib)
        num1 = num2
    return fib

fibo = fibonacci(4000000)

even = []

for item in fibo:
    if item % 2 == 0:
        even.append(item)

print even
print sum(even)
